const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_POST = 'FETCH_POST';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
const DELETE = 'DELETE';
const LIKE = 'LIKE';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const COMMENT = 'COMMENT';

export { CREATE, UPDATE, FETCH_ALL, FETCH_BY_SEARCH, FETCH_POST, DELETE, LIKE, AUTH, LOGOUT, START_LOADING, END_LOADING, COMMENT };