const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
const DELETE = 'DELETE';
const LIKE = 'LIKE';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING'

export { CREATE, UPDATE, FETCH_ALL, FETCH_BY_SEARCH, DELETE, LIKE, AUTH, LOGOUT, START_LOADING, END_LOADING };